### PR TITLE
Add commit message limit

### PR DESCRIPTION
**Pull request by manuel-uberti**
This is an attempt at answering this feature request: https://github.com/clemera/dired-git-info/issues/3

Let me know if you need me to change anything, or feel free to close if you're not interested in this kind of customisation.

### CODE REVIEW

**Comment by clemera** [comment]
Did you sign the FSF copyright assignment? If not, do you want to [sign](https://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future) it? `dired-git-info` is on GNU ELPA and this is required. 

Regarding your contribution, I would like to indicate that the string was truncated by adding a "..."  to its end. Other than that, this looks good to me, thank you!

**Comment by manuel-uberti** [comment]
Yes, I  have the CA, since I already contributed to `ivy`.

**Comment by manuel-uberti** [comment]
Actually, sorry, that came out a bit rude. I did sign the CA a while ago, but I don't remember if I signed it with the email I am currently using on GitHub.

Let me know if you need me to sign it with the current email, I'll be glad to.

**Comment by clemera** [comment]
> Yes, I have the CA!

Great!

> Let me know if you need me to sign it with the current email

Not necessary, thanks. Would you like to add the code for printing "..." for the truncated part? Now that I'm thinking about it, the best solution would probably to compute if the lines wrap and truncate from there, which was the intention for submitting #3 I guess.

**Comment by manuel-uberti** [comment]
I'll see what I can do.

**Comment by manuel-uberti** [comment]
Could you please check if this is the desired effect?

**Comment by clemera** [comment]
I have implemented an alternate solution with 9f34bd7b462ca39455f4036d3afab06661620444.

**Comment by clemera** [comment]
Thanks for you efforts anyway!

**Comment by manuel-uberti** [comment]
Cool, thank you.

**Pull request closed without merging**
